### ISSUE TITLE
Pasar memoria doc a latex

### ISSUE THREAD

**Issue by aos0020** [cgc1007/cgc1007angelodls#22]
- Revisar imágenes.
- Revisar bibliografía.
- bibentry (http://gking.harvard.edu/files/bibentry2.pdf).

**Documentación**

- [x]  Resumen
- [x]  Introducción
- [x]  Objetivos del proyecto
- [x]  Conceptos teóricos
- [x]  Técnicas y herramientas
- [x]  Aspectos relevantes
- [x]  Trabajos relacionados
- [x]  Conclusiones y Líneas de trabajo futuras

**Comment by cgc1007** [comment]
Expresión regular para corregir las referencias:

Buscar: (\{\[\})([\w:\\]+)(\{\]\}\\\_)
Reemplazar por: \\citep{\2}
Ej: {[}art:campbell2005{]}\_ -> \citep{art:campbell2005}

**Comment by cgc1007** [comment]
Cheat-sheet plantilla
Rutas de ficheros / paquetes
\ruta{C:/Windows/System32}
Imágenes
Imagen en el sitio introducido:

\imagen{nombre-img}{Descripción...}
Imagen flotante:

\imagenflotante{nombre-img}{Descripción...}
El nombre de la imagen sin extensión.
