### ISSUE TITLE
Resources$NotFoundException con vectores en Android < 21

### ISSUE THREAD

**Issue by aos0020** [cgc1007/cgc1007angelodls#24]
https://medium.com/@chrisbanes/appcompat-v23-2-age-of-the-vectors-91cbafa87c88#.u93ttzjpb

**Comment by cgc1007** [comment]
https://github.com/davidmigloz/go-bees/issues/181#issuecomment-275909057

**Comment by cgc1007** [comment]
![image](https://user-images.githubusercontent.com/93854941/142770396-a9e10096-2c2b-43aa-8e74-175d49a73fd6.png)
