### ISSUE TITLE
Publicar en Google Play

### ISSUE THREAD

**Issue by aos0020** [cgc1007/cgc1007angelodls#28]
https://support.google.com/googleplay/android-developer/answer/113469#privacy

https://www.raywenderlich.com/122114/android-app-distribution-tutorial-zero-google-play-store

**Comment by cgc1007** [comment]
apiaries-management
apiary-information
hives-management
hives-flight-activity-recordings
hive-flight-activity-recording
hive-flight-activity-monitoring

**Comment by cgc1007** [comment]
https://play.google.com/store/apps/details?id=com.davidmiguel.gobees
