### ISSUE TITLE
Entrega TFG

### ISSUE THREAD

**Issue by aos0020** [cgc1007/cgc1007angelodls#38]
**Secretaría:**
 
- [ ] Memoria en formato impreso.
- [ ]  Cinco discos memoria, anexos, fuentes del proyecto, aplicación, otros recursos (videos, máquinas virtuales, software open source de terceros...) .
- [ ]  Un disco con la memoria y anexos con dos resúmenes del trabajo (español y inglés).
- [ ]  Impresos de solicitud.

**UbuVirtual**

- [ ]  Memoria y anexos en asignatura TFG.
- [ ]  Memoria y anexos en comunidad TFG.

Junto con el procedimiento de entrega fijado por el tribunal de TFG en la Secretaría Académica del centro, adicionalmente hay que depositar en UBUVirtual una copia del documento(s) pdf (bien con la memoria completa, o bien desglosada en memoria y anexos).

Este procedimiento es adicional, y NO sustituye en ningún caso a la entrega en Secretaría Académica del centro.

La tarea para realizar dicha entrega la tenéis disponible en el siguiente enlace,dentro de la comunidad habilitada para tal efecto (Comunidad de Trabajo Fin de Grado en Ingeniería Informática).

El nombre del fichero debe seguir el siguiente formato (si se entrega un único fichero):

GII_apellido1_apellido2_nombre_Enero_ 2017.pdf

o bien (si se entrega en dos partes):

GII_apellido1_apellido2_nombre_Enero_2017_memoria.pdf

GII_apellido1_apellido2_nombre_Enero_2017_anexos.pdf

**Comment by cgc1007** [comment]
Impresos
impreso_biblioteca.docx
impreso_entrega_tfg.docx
