### ISSUE TITLE
Revisiones de colmenas

### ISSUE THREAD

**Issue by aos0020** [cgc1007/cgc1007angelodls#42]
Añadir que cada colmena pueda tener cero o más revisiones.

Una revisión sería un formulario con los principales puntos que mira un apicultor cuando revisa una colmena. De tal manera, que el apicultor pueda guardar fácilmente los resultados de la inspección y pueda acceder al histórico de cada colmena.

**Comment by cgc1007** [comment]
![image](https://user-images.githubusercontent.com/93854941/142772516-73b0c524-9823-4698-ab5b-f18b1ec4d0f1.png)
https://mundoabejas.com/es/blog/ficha-de-control-de-colmenas-b79.html
