### ISSUE TITLE
Export Database

### ISSUE THREAD

**Issue by aos0020** [cgc1007/cgc1007angelodls#46]
- https://medium.com/glucosio-project/example-class-to-export-import-a-realm-database-on-android-c429ade2b4ed#.frlec0tg9
- https://medium.com/glucosio-project/backup-restore-a-realm-database-on-google-drive-with-drive-api-c238515a5975#.byhqh6vxc
- https://medium.com/glucosio-project/backup-restore-a-realm-database-on-google-drive-with-drive-api-c238515a5975#.byhqh6vxc

**Comment by cgc1007** [comment]
Version 1.3
